# Generated by Django 4.2.8 on 2024-05-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
