# Generated by Django 4.2.8 on 2024-05-30 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0002_alter_application_application_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('selection_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('selection_time', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='ats.application')),
            ],
        ),
    ]
