# Generated by Django 4.2.8 on 2024-02-01 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_resume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='resume_file',
            new_name='resume_base64',
        ),
    ]
